#!/usr/bin/env python3
"""Download Gen-1 Pokémon sprites and convert to 1-bit XBM arrays for u8g2/ESP32 (PROGMEM)."""

import requests
from PIL import Image, ImageFilter
import io, sys, os

POKEMON = [
    # Must match kPokemon[] order in main.cpp exactly
    # NORMAL
    (35,  "clefairy"),
    (39,  "jigglypuff"),
    (52,  "meowth"),
    (133, "eevee"),
    (143, "snorlax"),
    # FIRE
    (4,   "charmander"),
    (37,  "vulpix"),
    (38,  "ninetales"),
    (136, "flareon"),
    (126, "magmar"),
    (146, "moltres"),
    # WATER
    (7,   "squirtle"),
    (54,  "psyduck"),
    (130, "gyarados"),
    (134, "vaporeon"),
    (131, "lapras"),
    # GRASS
    (1,   "bulbasaur"),
    # ELECTRIC
    (25,  "pikachu"),
    (81,  "magnemite"),
    (135, "jolteon"),
    (125, "electabuzz"),
    (145, "zapdos"),
    # ICE
    (144, "articuno"),
    # FIGHTING
    (66,  "machop"),
    (57,  "primeape"),
    # POISON
    (24,  "arbok"),
    (34,  "nidoking"),
    # PSYCHIC
    (65,  "alakazam"),
    (150, "mewtwo"),
    (151, "mew"),
    # GHOST
    (93,  "haunter"),
    (94,  "gengar"),
    # DRAGON
    (147, "dratini"),
    (148, "dragonair"),
    (149, "dragonite"),
    # ROCK
    (74,  "geodude"),
    (95,  "onix"),
    (142, "aerodactyl"),
    # GROUND
    (50,  "diglett"),
    (112, "rhydon"),
    # BUG
    (12,  "butterfree"),
    (123, "scyther"),
]

# 48×48 fits well in the left 56px of the 128×128 OLED (leaves room for icon/text at top)
SPRITE_SIZE = 48  # must be multiple of 8

assert SPRITE_SIZE % 8 == 0
BYTES_PER_ROW = SPRITE_SIZE // 8
BYTES_PER_SPRITE = BYTES_PER_ROW * SPRITE_SIZE


def download_sprite(dex_id: int) -> bytes:
    """Try multiple sources for the sprite PNG, prefer Gen-1 pixel art style."""
    # Source 1: pokemondb Red/Blue sprite (56×56 Game Boy pixel art)
    urls = [
        f"https://img.pokemondb.net/sprites/red-blue/normal/{POKEMON[[x[0] for x in POKEMON].index(dex_id)][1]}.png",
        # Fallback: PokeAPI official home sprite (higher res, will be resized)
        f"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/{dex_id}.png",
    ]
    for url in urls:
        try:
            r = requests.get(url, timeout=8)
            if r.status_code == 200:
                return r.content
        except Exception:
            continue
    raise RuntimeError(f"Could not download sprite for #{dex_id}")


def to_xbm_bytes(img_bytes: bytes) -> bytes:
    """
    Convert PNG bytes → 1-bit XBM for u8g2 drawXBM.
    XBM format: LSB-first bit order — bit 0 = leftmost pixel.
    Black (dark) pixels = bit set (1), white/transparent = 0.
    """
    img = Image.open(io.BytesIO(img_bytes)).convert("RGBA")

    # Composite onto white background to flatten transparency
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    gray = bg.convert("L")

    # Resize with high-quality filter
    gray = gray.resize((SPRITE_SIZE, SPRITE_SIZE), Image.LANCZOS)

    # Slight sharpening helps small sprites stay crisp
    gray = gray.filter(ImageFilter.SHARPEN)

    # Threshold: pixels < 160 are "dark" → set bit (drawn)
    data = []
    for y in range(SPRITE_SIZE):
        for bx in range(BYTES_PER_ROW):
            byte = 0
            for bit in range(8):
                x = bx * 8 + bit
                if gray.getpixel((x, y)) < 160:
                    byte |= (1 << bit)  # LSB = leftmost pixel
            data.append(byte)
    return bytes(data)


def main():
    out_path = os.path.join(os.path.dirname(__file__), "../src/pokemon_sprites.h")

    lines = [
        "#pragma once",
        "// Auto-generated by tools/gen_pokemon_sprites.py — do not edit.",
        "// 1-bit XBM sprites for u8g2 drawXBM(), stored in ESP32 flash (PROGMEM).",
        "#include <pgmspace.h>",
        "",
        f"#define PKMN_SPRITE_SIZE  {SPRITE_SIZE}   // width == height in pixels",
        f"#define PKMN_SPRITE_BYTES {BYTES_PER_SPRITE}  // bytes per sprite",
        "",
    ]

    names = []
    for dex_id, name in POKEMON:
        varname = f"pkmn_spr_{name.replace('-', '_')}"
        names.append(varname)
        print(f"  #{dex_id:3d} {name:<12s} ... ", end="", flush=True)
        try:
            raw = download_sprite(dex_id)
            xbm = to_xbm_bytes(raw)
            assert len(xbm) == BYTES_PER_SPRITE, f"Expected {BYTES_PER_SPRITE} bytes, got {len(xbm)}"
            hex_str = ", ".join(f"0x{b:02x}" for b in xbm)
            lines.append(f"static const uint8_t {varname}[{BYTES_PER_SPRITE}] PROGMEM = {{{hex_str}}};")
            print(f"OK ({len(xbm)} B)")
        except Exception as e:
            print(f"FAILED: {e}")
            lines.append(f"static const uint8_t {varname}[{BYTES_PER_SPRITE}] PROGMEM = {{{', '.join(['0x00']*BYTES_PER_SPRITE)}}};")

    lines += [
        "",
        f"// Pointer table — index matches kPokemon[] in main.cpp",
        f"static const uint8_t* const kPkmnSprites[{len(names)}] PROGMEM = {{",
    ]
    for n in names:
        lines.append(f"    {n},")
    lines.append("};")
    lines.append("")

    content = "\n".join(lines)
    with open(out_path, "w") as f:
        f.write(content)

    total = len(names) * BYTES_PER_SPRITE
    print(f"\nWrote {out_path}")
    print(f"  {len(names)} sprites × {BYTES_PER_SPRITE} B = {total} B ({total/1024:.1f} KB) in flash")


if __name__ == "__main__":
    main()
